import json
import os
import time
import matplotlib.pyplot as plt
import numpy as np
import requests

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import (
    ModelTypes,
    DecodingMethods,
)

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


# Descargar y leer el archivo de texto
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/1r_mM6ZPYNxcFv65QkzubA/California-Culinary-Map.txt"
response = requests.get(url)
with open("California-Culinary-Map.txt", "w", encoding="utf-8") as f:
    f.write(response.text)

### 1.1: Define the file_path to the text file
file_path = "California-Culinary-Map.txt"

### 1.2: Open the text file
with open(file_path, 'r') as file:
    data = file.read()

### 1.3: Print the first 100 characters of the restaurant data
print(data[:100])


### 2.1: Split the restaurant paragraphs into list (hint: use .split('\n\n'))
restaurant_list = data.split('\n\n')

### 2.2: Since the first item is the dataset name, we remove it
restaurant_list = restaurant_list[1:]

### 2.3: Print out the number of restaurants we have (hint: use the len() function)
print(len(restaurant_list))

### 2.4: Print out the first item to have a closer look at the content
print(restaurant_list[0])


def llm_model(system_msg, prompt_txt):
    # system_msg: the system message given to the LLM
    # prompt_txt: the user prompt
    
    model_id = "ibm/granite-4-h-small"
    project_id = "skills-network"

    credentials = Credentials(
        url="https://us-south.ml.cloud.ibm.com",
    )

    ### 1.1: Define the model by ModelInference
    model = ModelInference(
        model_id=model_id,
        credentials=credentials,
        project_id=project_id
    )

    ### 1.2: Define the messages
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": prompt_txt}
    ]

    ### 1.3: Get the final response output and return it
    response = model.chat(messages=messages)
    output_text = response["choices"][0]["message"]["content"]
    
    return output_text


def safe_llm_call(system_msg, prompt_txt, retries=3):
    for i in range(retries):
        try:
            return llm_model(system_msg, prompt_txt)
        except Exception:
            time.sleep(2)
    return "Failed after retries"


# Prueba rápida de la función segura
system_msg = "You are a helpful assistant."
prompt_txt = "Which place is warmer in winter? Hawaii or Greenland?"
print(safe_llm_call(system_msg, prompt_txt))


EXAMPLE_RESTAURANT_PARAGRAPH = restaurant_list[1]  # use the second restaurant paragraph as the example
EXAMPLE_OUTPUT = """
    {
    "name": "Mar de Cortez",
    "location": "Santa Monica",
    "type": "casual taqueria",
    "food_style": "Baja-style seafood",
    "rating": 4.2,
    "price_range": 1,
    "signatures": [
        "beer-battered snapper tacos",
        "zesty octopus ceviche"
    ],
    "vibe": "salt-air energy",
    "environment": "a premier sun-drenched spot for open-air dining near the pier.",
    "shortcomings": []
    }
"""


### Design your prompt here
def restaurant_data_structure_prompt_generation(restaurant_paragraph):
    base_system_msg = f"""
    You are an restaurant specialized assistant , your work is to convert plain text descriptions from restaurants into a well structured
    format JSON using the following fields:
    {{
        "name": "",
        "location": "",
        "type": "",
        "food_style": "",
        "rating": 0.0,
        "price_range": 0,
        "signatures": [],
        "vibe": "",
        "environment": "",
        "shortcomings": []
    }}
    """
    
    base_user_prompt = f"""
    Task:
    Extract the restaurant information below and return it as a format JSON like the one's from the example above. Don't invent any data.
    If a field is not mentioned in the description, use null (or an empty list for signatures/shortcomings). Do not infer or guess missing information.

    Restaurant description:
    {restaurant_paragraph}

    Example:
    Input Restaurant Description: {EXAMPLE_RESTAURANT_PARAGRAPH}
    Output:
    {EXAMPLE_OUTPUT}
    """
    return base_system_msg, base_user_prompt


# Unit test:
restaurant_paragraph = restaurant_list[3]
base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(restaurant_paragraph=restaurant_paragraph)

test_response = llm_model(system_msg=base_system_msg, prompt_txt=base_user_prompt)
print(test_response)


# Validation
from pydantic import BaseModel, Field, ValidationError
from typing import List, Optional

### 3.1. Define the schema
class Restaurant(BaseModel):
    name: str
    location: str
    type: str
    food_style: str
    rating: Optional[float] = None
    price_range: Optional[int] = None
    signatures: List[str] = Field(default_factory=list)
    vibe: Optional[str] = None
    environment: str
    shortcomings: List[str] = Field(default_factory=list)


### 3.2. Use the validation method to validate the test_response from the unit test
try:
    restaurant_data = Restaurant.model_validate_json(test_response)
    print(f"Success! Validated: {restaurant_data.name}")
except ValidationError as e:
    print(f"Validation failed: {e.json()}")


def JSON_auto_repair_prompts(candidate_json_output, error_message):
    auto_repair_system_msg = """
    Eres un asistente especializado en corregir JSON mal formado según un esquema específico. 
    Se te dará un JSON con errores y el mensaje de error de validación. 
    Tu trabajo es corregir el JSON para que cumpla el esquema, sin cambiar la información real que ya contiene.
    """
    auto_repair_prompt = f"""
    Task: El siguiente JSON no pasó la validación. Corrígelo basándote en el error indicado.

    JSON con errores:
    {candidate_json_output}

    Error de validación:
    {error_message}

    Devuelve únicamente el JSON corregido, sin explicaciones adicionales.
    """
    return auto_repair_system_msg, auto_repair_prompt


### 2.3: Process the entire restaurant list with validation and auto-correction
structured_restaurant_lists = []
for idx, restaurant_paragraph in enumerate(restaurant_list):
    ### 2.1: Produce your initial output
    base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(restaurant_paragraph)
    candidate_json_output = safe_llm_call(system_msg=base_system_msg, prompt_txt=base_user_prompt)

    ### 2.2: Validation and Auto Correction loop on the output 
    retry_count = 0
    while retry_count < 10:
        try:
            restaurant_data = Restaurant.model_validate_json(candidate_json_output)
            print(f"Success! Validated: {restaurant_data.name}")
            break
        except ValidationError as e:
            msg_error = e.json()
            new_system_msg_rep, new_prompt_repaired = JSON_auto_repair_prompts(candidate_json_output, msg_error)
            new_test_response = safe_llm_call(system_msg=new_system_msg_rep, prompt_txt=new_prompt_repaired)
            candidate_json_output = new_test_response
            retry_count += 1

    ### 2.3: Append your finalized response to the structured_restaurant_lists
    structured_restaurant_lists.append(restaurant_data)

    # A manual progress bar
    if (idx + 1) % 20 == 0:
        print(f'{idx + 1} out of {len(restaurant_list)} is done')

# A final message to notify the completion
print('ALL DONE!!')


### Print the 50th item in the structured_restaurant_lists
print(structured_restaurant_lists[49])

# Convert objects to dictionaries
structured_restaurant_lists_json = [response.model_dump() for response in structured_restaurant_lists]

# For each item in the restaurant list, assign it with an itemId to be consistent with the user review data:
for i, response in enumerate(structured_restaurant_lists_json):
    response['itemId'] = 1000001 + i
    structured_restaurant_lists_json[i] = response
    
filename = 'structured_restaurant_data.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(structured_restaurant_lists_json, f, indent=4)